### ISSUE TITLE
Map postgres errors

### ISSUE THREAD

**Issue by jmeas** [jmeas/api-pls#1]
Right now, postgres errors will be reported as generic server errors. I can do better than that. For instance, hitting an endpoint for a resource that doesn't exist in the DB returns the generic error, yet the logged err is:

```sh
16:33:01.294Z  WARN JSON-API-Builder: There was an unknown server error. (err.code=42P01)
    error: relation "transaction" does not exist
        at Connection.parseE (/Users/jmeas/webdev/json-api-builder/node_modules/pg/lib/connection.js:539:11)
        at Connection.parseMessage (/Users/jmeas/webdev/json-api-builder/node_modules/pg/lib/connection.js:366:17)
        at TLSSocket.<anonymous> (/Users/jmeas/webdev/json-api-builder/node_modules/pg/lib/connection.js:105:22)
        at emitOne (events.js:96:13)
        at TLSSocket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:176:18)
        at TLSSocket.Readable.push (_stream_readable.js:134:10)
        at TLSWrap.onread (net.js:551:20)
```

I can use `err.code` to map these to more human-readable things.

List of postgres errors: https://www.postgresql.org/docs/8.2/static/errcodes-appendix.html

**Comment by jmeas** [comment]
Gonna close...doesn't seem super important right now. The # of times when there is a query error should be relatively small, given how many checks the system goes through before actually making a query (resource must be defined, request must be feasible, etc)>
