### ISSUE TITLE
Resolve intermittent careen errors on startup

### ISSUE THREAD

**Issue by jmeas** [jmeas/api-pls#16]
~~For some reason, the files that I'm deleting with del are still getting picked up by careen...even after they're gone. I'm not sure what could be causing that...~~

Careen intermittently errors on startup with the following error:

```
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at matchesToMigration (/Users/jmeas/webdev/json-api-builder/node_modules/careen/lib/files.js:81:54)
    at /Users/jmeas/webdev/json-api-builder/node_modules/ramda/dist/ramda.js:3865:27
    at /Users/jmeas/webdev/json-api-builder/node_modules/ramda/dist/ramda.js:920:27
    at XWrap.f (/Users/jmeas/webdev/json-api-builder/node_modules/ramda/dist/ramda.js:5350:24)
    at XWrap.@@transducer/step (/Users/jmeas/webdev/json-api-builder/node_modules/ramda/dist/ramda.js:755:25)
```

**Comment by jmeas** [comment]
Alright, so the issue isn't with ghost deleted files. The same (correct) list of files are picked up always by careen. The issue is that reading those files, or something, is exploding sometimes. This is where the issue is:

`R.find(R.propEq(3, 'up'), matches)`

**Comment by jmeas** [comment]
This is no longer an issue with the new startup system introduced in #48

**Comment by jmeas** [comment]
This is still an issue.

I think I'll be migrating off of careen, to a modified version of [this lib](https://github.com/dmitriiabramov/node-sql-migrations). They work similarly, but careen's code is TS+Ramda, neither of which I know.
